version: '2'

services:
  nginx:
    image: api-nginx:latest
    build:
      context: .
      dockerfile: nginx/Dockerfile
    ports:
      - 5000:5000
  api:
    image: api:latest
    build:
      context: .
      dockerfile: api/Dockerfile
    environment:
      NODE_ENV: production 
    ports:
      - 8080:5000
    links:
      - db
      - es
  api2:
    image: api:latest
    build:
      context: .
      dockerfile: api/Dockerfile
    environment:
      NODE_ENV: production 
    ports:
      - 8082:5000
    links:
      - db
      - es
  api3:
    image: api:latest
    build:
      context: .
      dockerfile: api/Dockerfile
    environment:
      NODE_ENV: production 
    ports:
      - 8081:5000
    links:
      - db
      - es
  db:
    image: mongo
    ports:
      - 27017:27017
  es:
    image: elasticsearch:2.4
    ports:
      - 9200:9200
      - 9300:9300