
version: '2'

services:
  api:
    image: api:latest
    build:
      context: .
      dockerfile: api/Dockerfile
    environment:
      NODE_ENV: production 
    volumes: 
      - ./api/:/usr/src/app
    ports:
      - 5000:5000
    links:
      - db
      - es
  db:
    image: mongo
    ports:
      - 27017:27017
  es:
    image: elasticsearch
    ports:
      - 9200:9200
      - 9300:9300